name: food_distribution_network
description: An intelligent food distribution network application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  intl: ^0.18.1
  http: ^1.1.0
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  youtube_player_flutter: ^9.1.1
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  google_generative_ai: ^0.2.0
  path: ^1.8.3
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png